/*
 * This source file was generated by the Gradle 'init' task
 */
package cutenotes;

//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
import javafx.application.Application;
import javafx.scene.control.*;
import javafx.scene.input.KeyCombination;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;


public class App extends Application{
    TextArea textArea;;
    @Override

    public void start(Stage stage){

        /*   MenuBar   */
        MenuBar menuBar = new MenuBar();
        //drop down menu
        Menu file = new Menu("File");
        Menu edit = new Menu("Edit");

       //drop down options 'menu items'
        var mNew = new MenuItem("New");
        var mOpen = new MenuItem("Open...");
        var mSave = new MenuItem("Save");
        var miFind = new MenuItem("Find");

        //saving shortcut
        mSave.setAccelerator(KeyCombination.keyCombination("Ctrl+S"));

        //attach edit's menu options
        edit.getItems().addAll(miFind);

        //attach file's menu options
        file.getItems().addAll(mNew, new SeparatorMenuItem(), mOpen, mSave);

        //attach the drop tab menu options to the bar
        menuBar.getMenus().addAll(file, edit);

        //get list of default fonts available in java
        ComboBox<String> fontSelector = new ComboBox<>();
        fontSelector.getItems().addAll(Font.getFamilies());
        //set a default value
        fontSelector.setValue("Arial");
        //set size of font selector
        fontSelector.setPrefWidth(100);

        /* FONT TOOLBAR*/
        Label fontSizeLabel = new Label("Font Size:");
        Spinner<Integer> fontSizeSpinner = new Spinner<>(10, 40, 14);
        fontSizeSpinner.setEditable(true);


        ToolBar fontToolBar = new ToolBar(

                new Label("Font:"),
                fontSelector,

                new Separator(),

                new Label("Size"),
                fontSizeSpinner
        );



        /* TEXT AREA */
        textArea = new TextArea();
        textArea.setWrapText(true);
        textArea.setFont(Font.font("Arial",  14));

        /* FONT SIZE SPINNER*/
        fontSizeSpinner.valueProperty().addListener((obs, oldValue, newValue) ->
        {textArea.setFont(Font.font("Arial", newValue)); });

        /* LAYOUT */
        VBox top = new VBox(menuBar, fontToolBar);
        BorderPane root = new BorderPane();
        root.setTop(top);
        root.setCenter(textArea);

        //create a scene and set the width and height
        Scene myScene = new Scene(root, 800,600);

        //set up window
        stage.setTitle("CuteNote");
        stage.setScene(myScene);
        stage.show();


    }

    public static void main(String[] args){
        //CALL APPLICATION
        launch(args);
    }
}